### ISSUE TITLE
Add an Overview to use Request Finance's addStakeholders REST API endpoint

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/docs.request.network#29]
Towards #17 

# Definiton of Done

- [x] Add Templates section between SDK Package Reference and Protocol Architecture

![Image](https://github.com/RequestNetwork/docs.request.network/assets/2530913/e0588dca-d34c-4be7-8bd2-cfa070eec410)

- [x] Add a page that explains What the addStakeholders Template does and why it exists.
- [x] ~~Add a question to the FAQ that says "How can my app access requests created by Request Finance?" Link to the template page.~~ Moved to #25 
- [x] Link to [RF Docs](https://docs.request.finance/faq#i-am-integrating-the-request-network.-can-i-get-access-to-users-data-on-request-finance)

**Comment by skiv71** [comment]
@MantisClone the FAQ section does not seem to appear in my edit view or the public docs (as yet). Is it in another change request?

**Comment by MantisClone** [comment]
No the FAQ CR is not make yet.
