### ISSUE TITLE
Add an exhaustive list of all the Request Network smart contracts

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/docs.request.network#30]
# Problem

Builders must go to the smart-contracts [lib/artifacts](https://github.com/RequestNetwork/requestNetwork/tree/master/packages/smart-contracts/src/lib/artifacts) folder in GitHub to see all the smart contract addresses.

# Possible Solutions

- Include smart contract addresses in the [Supported chains](https://docs.request.network/get-started/supported-chains) table
- Add an exhaustive list of all smart contracts to the [Contracts](https://docs.request.network/get-started/contracts) page.

# Inspiration
- Consider using the same format as other established protocols. For example, [Compound](https://docs.compound.finance/#networks) uses an accordion (tabs) with a table on each tab with columns: Contract name, Contract address.

![Image](https://github.com/RequestNetwork/docs.request.network/assets/2530913/d57bf48b-21ce-4e57-8307-9ccd59298080)

**Comment by MantisClone** [comment]
Consider using the same format as other established protocols. For example, [Compound](https://docs.compound.finance/#networks) uses an accordion (tabs) with a 2-column table on each tab with columns: Contract name, Contract address.

**Comment by aimensahnoun** [comment]
Added the available smart contract list , changes can be seen in this **[Preview](https://app.gitbook.com/o/-LBPEk9k7ap5J4UBioon/s/ei6UAiSK3iAAi0mFH667/~/revisions/bdX5ULEcINb65Ox8LGEa/)** url.

**Comment by aimensahnoun** [comment]
Updated smart contract list based on Feedback , [preview url](https://docs.request.network/~/changes/3g95H1F6Ow1U25iosZxT/get-started/protocol-overview/smart-contract-addresses).
