### ISSUE TITLE
While following the doc, tsc was throwing error

### ISSUE THREAD

**Issue by akp111** [RequestNetwork/docs.request.network#6]
<img width="1193" alt="image" src="https://github.com/RequestNetwork/docs.request.network/assets/38760485/8b41b88b-1e77-4446-abfe-cf0c71f34ee3">
After going through sdk, found the right TYPE

**Comment by alexandre-abrioux** [comment]
fixed in https://github.com/RequestNetwork/docs.request.network/pull/5
