### ISSUE TITLE
Document wagmi changes

### ISSUE THREAD

**Issue by aimensahnoun** [RequestNetwork/docs.request.network#70]
- Update the web component docs to showcase new `wagmi-config` integration

**Comment by aimensahnoun** [comment]
Open a Change request https://app.gitbook.com/o/-LBPEk9k7ap5J4UBioon/s/ei6UAiSK3iAAi0mFH667/~/changes/109/building-blocks/components/invoice-dashboard

**Comment by MantisClone** [comment]
Resolved in 320cf515a43115b4c18628148e3ee6a6d7d5ba83
